#!/usr/bin/env python3
"""Disposable Elice Ubuntu/Python 3.10 instance bootstrap (no credentials stored)."""

import argparse
import json
import os
from pathlib import Path
import platform
import shlex
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
MODELS = ("grounding", "comotion", "multihmr2", "motiongpt", "mgllm")
REPOS = {
    "comotion": (
        "ml-comotion",
        "apple/ml-comotion",
        "04b035af79a68267f6bb722b61bf5f13cb2b0068",
    ),
    "multihmr2": (
        "multi-hmr2",
        "naver/multi-hmr2",
        "f066532d096034700e5ba8b7b1ca655729d3ea6e",
    ),
    "motiongpt": (
        "MotionGPT",
        "OpenMotionLab/MotionGPT",
        "001aaca8d0ee218fc17f8265d11ac124044fe42f",
    ),
    "mgllm": (
        "MG-MotionLLM",
        "BizhuWu/MG-MotionLLM",
        "b8e6df126197609dc692686991fff2c1703eb217",
    ),
}
ENV = {
    "grounding": "grounding_env",
    "comotion": "pose_env",
    "multihmr2": "pose_env",
    "motiongpt": "env",
    "mgllm": "env",
}
ASSETS = {
    "grounding": [],  # selected HF grounding weights are fetched on first inference
    "comotion": [
        "assets/SMPL_NEUTRAL.pkl",
        "ml-comotion/src/comotion_demo/data/comotion_detection_checkpoint.pt",
        "ml-comotion/src/comotion_demo/data/comotion_refine_checkpoint.pt",
    ],
    "multihmr2": ["multi-hmr2/checkpoints/multihmr2.pt"],
    "motiongpt": [
        "assets/motiongpt_s3_h3d.tar",
        "assets/reference_joints.npy",
        "assets/reference_features.npy",
        "MotionGPT/assets/meta/mean.npy",
        "MotionGPT/assets/meta/std.npy",
    ],
    "mgllm": [
        "assets/t2m.zip",
        "MG-MotionLLM/checkpoints/pretrained_vqvae/t2m.pth",
        "assets/mgllm_m2t/config.json",
        "assets/mgllm_m2dt/config.json",
    ],
}


def run(args, **kwargs):
    print("+", shlex.join(map(str, args)), flush=True)
    return subprocess.run(list(map(str, args)), check=True, **kwargs)


def write_env(workspace):
    values = {
        "MOTION_WORKSPACE": workspace,
        "GROUNDING_PYTHON": workspace / "grounding_env/bin/python",
        "POSE_PYTHON": workspace / "pose_env/bin/python",
        "CAPTION_PYTHON": workspace / "env/bin/python",
    }
    (workspace / "env.sh").write_text(
        "# Generated by AIM setup; source this file after SSH login.\n"
        + "".join(f"export {k}={shlex.quote(str(v))}\n" for k, v in values.items())
    )


def host_check():
    if platform.system() != "Linux" or platform.machine() not in ("x86_64", "AMD64"):
        raise RuntimeError(
            "Installation requires Ubuntu x86_64; use --dry-run on this host."
        )
    if sys.version_info[:2] != (3, 10):
        raise RuntimeError(
            "Run with python3.10 (select an Ubuntu 22.04 / Python 3.10 image)."
        )
    run(["nvidia-smi"])


def checkout(workspace, model):
    folder, repo, sha = REPOS[model]
    dst = workspace / folder
    if dst.exists():
        # Never reset a user's model source, even if it is on another revision.
        head = subprocess.check_output(
            ["git", "-C", str(dst), "rev-parse", "HEAD"], text=True
        ).strip()
        dirty = subprocess.check_output(
            ["git", "-C", str(dst), "status", "--porcelain", "--untracked-files=no"],
            text=True,
        ).strip()
        if head != sha or dirty:
            raise RuntimeError(
                f"{dst}: revision differs or tracked files modified; use a fresh workspace."
            )
    else:
        run(["git", "init", dst])
        run(
            [
                "git",
                "-C",
                dst,
                "remote",
                "add",
                "origin",
                f"https://github.com/{repo}.git",
            ]
        )
        run(["git", "-C", dst, "fetch", "--depth", "1", "origin", sha])
        run(["git", "-C", dst, "checkout", "--detach", "FETCH_HEAD"])
    return dst


def install(workspace, models):
    host_check()
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "assets").mkdir(exist_ok=True)
    write_env(workspace)
    completed = set()
    for model in models:
        name = ENV[model]
        py = workspace / name / "bin/python"
        if name not in completed:
            if not py.exists():
                run([sys.executable, "-m", "venv", workspace / name])
            run(
                [
                    py,
                    "-m",
                    "pip",
                    "install",
                    "pip==25.2",
                    "setuptools==80.9.0",
                    "wheel==0.45.1",
                ]
            )
            # Match the tested 20260916 pose/caption Torch line; newer GPU arches need separate validation.
            torch, vision, cuda = (
                ("2.6.0", "0.21.0", "cu124")
                if model == "grounding"
                else ("2.5.1", "0.20.1", "cu121")
            )
            run(
                [
                    py,
                    "-m",
                    "pip",
                    "install",
                    f"torch=={torch}",
                    f"torchvision=={vision}",
                    "--index-url",
                    f"https://download.pytorch.org/whl/{cuda}",
                ]
            )
            req = (
                "grounding"
                if model == "grounding"
                else ("pose" if name == "pose_env" else "caption")
            )
            # Prevent transitive dependencies from silently replacing the intended torch wheel.
            constraints = workspace / f"{name}-torch.txt"
            constraints.write_text(f"torch=={torch}\ntorchvision=={vision}\n")
            run(
                [
                    py,
                    "-m",
                    "pip",
                    "install",
                    "-c",
                    constraints,
                    "-r",
                    ROOT / f"requirements/elice/{req}.txt",
                ]
            )
            if name == "pose_env":
                run(
                    [
                        py,
                        "-m",
                        "pip",
                        "install",
                        "--no-build-isolation",
                        "--no-deps",
                        "chumpy @ git+https://github.com/mattloper/chumpy@9b045ff5d6588a24a0bab52c83f032e2ba433e17",
                    ]
                )
                # Upstream pins OpenGL 3.1.0; OSMesa needs the selected 3.1.7. All other deps are above.
                run([py, "-m", "pip", "install", "--no-deps", "pyrender==0.1.45"])
            run(
                [
                    py,
                    "-c",
                    'import torch; assert torch.cuda.is_available(), "CUDA unavailable"; x=torch.ones((8,8),device="cuda"); print(torch.cuda.get_device_name(), (x@x).sum().item())',
                ]
            )
            completed.add(name)
        if model in REPOS:
            dst = checkout(workspace, model)
            if model in ("comotion", "multihmr2"):
                # Curated headless dependencies; avoid GUI/training extras and forced upgrades.
                run(
                    [
                        py,
                        "-m",
                        "pip",
                        "install",
                        "--no-build-isolation",
                        "--no-deps",
                        "-e",
                        dst,
                    ]
                )
        if model == "comotion":
            link = (
                workspace / "ml-comotion/src/comotion_demo/data/smpl/SMPL_NEUTRAL.pkl"
            )
            link.parent.mkdir(parents=True, exist_ok=True)
            target = workspace / "assets/SMPL_NEUTRAL.pkl"
            if not link.exists() and not link.is_symlink():
                link.symlink_to(target)
        freeze = subprocess.check_output([str(py), "-m", "pip", "freeze"], text=True)
        (workspace / f"{name}-freeze.txt").write_text(freeze)
    write_env(workspace)
    record = workspace / "setup-revisions.json"
    revisions = json.loads(record.read_text()) if record.exists() else {}
    revisions.update({m: REPOS[m] for m in models if m in REPOS})
    record.write_text(json.dumps(revisions, indent=2))
    print(
        "Dependencies installed. Next: assets, copy licensed/reference files, then check. NOT yet inference-ready."
    )


def assets(workspace, models):
    # Downloads run in the selected environments and use official distribution URLs.
    for model in models:
        py = workspace / ENV[model] / "bin/python"
        if not py.exists():
            raise RuntimeError(f"Install {model} first: missing {py}")
        if model == "grounding":
            print(
                "Grounding weights download on first inference for the selected --model."
            )
        elif model == "comotion":
            dst = workspace / "ml-comotion/src/comotion_demo/data"
            if not all(
                (dst / name).is_file() and (dst / name).stat().st_size
                for name in (
                    "comotion_detection_checkpoint.pt",
                    "comotion_refine_checkpoint.pt",
                )
            ):
                archive = workspace / "assets/comotion_checkpoints.tar.gz"
                run(
                    [
                        "curl",
                        "--fail",
                        "--location",
                        "--retry",
                        "3",
                        "https://ml-site.cdn-apple.com/models/comotion/demo_checkpoints.tar.gz",
                        "-o",
                        archive,
                    ]
                )
                run(["tar", "xzf", archive, "-C", dst])
            print("Copy your licensed SMPL_NEUTRAL.pkl to workspace/assets/.")
        elif model == "multihmr2":
            dst = workspace / "multi-hmr2/checkpoints/multihmr2.pt"
            dst.parent.mkdir(parents=True, exist_ok=True)
            if not dst.exists():
                tmp = dst.with_suffix(".part")
                run(
                    [
                        "curl",
                        "--fail",
                        "--location",
                        "--retry",
                        "3",
                        "https://download.europe.naverlabs.com/ComputerVision/MultiHMR/multihmr2.pt",
                        "-o",
                        tmp,
                    ]
                )
                tmp.replace(dst)
        elif model == "motiongpt":
            run(
                [
                    py,
                    "-c",
                    "from huggingface_hub import hf_hub_download, snapshot_download; import sys; hf_hub_download('OpenMotionLab/MotionGPT-base','motiongpt_s3_h3d.tar',local_dir=sys.argv[1]); snapshot_download('google/flan-t5-base',allow_patterns=['*.json','*.model','*.safetensors'])",
                    workspace / "assets",
                ]
            )
            if (workspace / "assets/reference_features.npy").exists():
                run([py, ROOT / "scripts/prepare_motion_reference.py", workspace])
            else:
                print(
                    "Restore assets/reference_features.npy, then run scripts/prepare_motion_reference.py using the caption Python."
                )
        elif model == "mgllm":
            run(
                [
                    py,
                    "-c",
                    "from huggingface_hub import snapshot_download; import sys; from pathlib import Path; [(snapshot_download('wbz0505/'+n+'-ft-from-GSPretrained-base',local_dir=Path(sys.argv[1])/('mgllm_'+n),allow_patterns=['*.json','*.model','pytorch_model.bin','*.safetensors'])) for n in ['m2t','m2dt']]",
                    workspace / "assets",
                ]
            )
            for filename, fileid in [
                ("t2m.zip", "1FIiqtkt4F-GVWmnBgtZnv9W3cPWS-oM-"),
                ("pretrained_vqvae.zip", "1tOw9wiu6jkzBy-bLe2iy47KAjE50DgjP"),
            ]:
                dst = workspace / "assets" / filename
                if not dst.exists():
                    tmp = dst.with_suffix(".part")
                    run(
                        [
                            py,
                            "-m",
                            "gdown",
                            f"https://drive.google.com/uc?id={fileid}",
                            "-O",
                            tmp,
                        ]
                    )
                    tmp.replace(dst)
            run([py, ROOT / "scripts/extract_vqvae.py", workspace])


def check(workspace, models):
    failed = False
    for model in models:
        print(f"[{model}]", flush=True)
        py = workspace / ENV[model] / "bin/python"
        required = [py] + [workspace / p for p in ASSETS[model]]
        if model in REPOS:
            required.append(workspace / REPOS[model][0])
        for path in required:
            ok = path.exists() and (not path.is_file() or path.stat().st_size > 0)
            print(("OK " if ok else "MISSING ") + str(path))
            failed |= not ok
        if py.exists():
            p = subprocess.run(
                [
                    str(py),
                    str(ROOT / "scripts/check_elice_model.py"),
                    model,
                    str(workspace),
                ]
            )
            failed |= p.returncode != 0
    print(
        "Environment checks passed; run a representative clip to validate model inference."
        if not failed
        else "NOT READY: resolve the missing files / failed checks above."
    )
    return 1 if failed else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["system", "install", "assets", "check"])
    parser.add_argument(
        "model", nargs="?", default="all", choices=(*MODELS, "pose", "all")
    )
    parser.add_argument(
        "--workspace",
        default=os.environ.get("MOTION_WORKSPACE", str(Path.home() / "aim-workspace")),
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    workspace = Path(args.workspace).expanduser().resolve()
    models = (
        list(MODELS)
        if args.model == "all"
        else (["comotion", "multihmr2"] if args.model == "pose" else [args.model])
    )
    if args.dry_run:
        print(
            json.dumps(
                {
                    "action": args.action,
                    "workspace": str(workspace),
                    "models": models,
                    "environments": {m: ENV[m] for m in models},
                    "repos": {m: REPOS[m] for m in models if m in REPOS},
                },
                indent=2,
            )
        )
        return 0
    if args.action == "system":
        if platform.system() != "Linux" or not Path("/etc/debian_version").exists():
            raise RuntimeError(
                "system requires Ubuntu/Debian; documented target is Ubuntu 22.04."
            )
        prefix = [] if os.geteuid() == 0 else ["sudo"]
        run(prefix + ["apt-get", "update"])
        run(
            prefix
            + [
                "apt-get",
                "install",
                "-y",
                "python3.10-venv",
                "python3.10-dev",
                "build-essential",
                "git",
                "curl",
                "ffmpeg",
                "libosmesa6-dev",
                "libglu1-mesa",
                "libgl1",
                "libglib2.0-0",
                "tmux",
            ]
        )
    elif args.action == "install":
        install(workspace, models)
    elif args.action == "assets":
        assets(workspace, models)
    else:
        return check(workspace, models)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
